# Generated by Django 5.0.6 on 2026-04-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='footer_image_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID for the footer logo', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='header_image_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID for the header logo', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='institution',
            field=models.CharField(blank=True, default='Prestige Institute of Engineering, Management and Research, Indore', max_length=255),
        ),
    ]
