# Generated by Django 5.0.6 on 2026-04-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_teacher_department_teacher_footer_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='default_semester',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='default_session',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
