# Generated by Django 5.0.6 on 2026-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='current_step',
            field=models.CharField(blank=True, help_text='Current stage of generation (Docs, Quiz, etc.)', max_length=255),
        ),
    ]
