# Generated by Django 5.0.6 on 2026-04-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lecture_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='session',
            field=models.CharField(blank=True, help_text='e.g. Jan-Jun 2026', max_length=100),
        ),
    ]
