# Generated by Django 5.0.6 on 2026-04-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_lecture_no_job_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='semester',
            field=models.CharField(blank=True, help_text='e.g. 4th', max_length=50),
        ),
    ]
