# Generated by Django 5.0.6 on 2026-04-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='subject_code',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='subject_name',
            field=models.CharField(blank=True, default='Generic', max_length=255),
        ),
    ]
